---
- hosts: all
  become: yes
  tasks:
  - name: install apache2
    apt:
      name: apache2
      update_cache: yes
      state: present
    notify:
    - restart_apache2
    when: ansible_os_family == "Debian"
  - name: install php packages
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - php
      - libapache2-mod-php
      - php-mcrypt 
      - php-mysql
    notify:
    - restart_apache2
    when: ansible_os_family == "Debian"
  - name: install httpd
    yum:
      name: httpd
      state: present
    notify:
    - restart_httpd
    when: ansible_os_family == "Redhat"
  - name: install php packages in centos
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - php
      - php-mysql
    notify:
    - restart_httpd
    when: ansible_os_family == "Redhat"
  handlers:
  - name: restart_apache2
    sercvice:
      name: apache2
      enabled: yes
      state: restarted
    when: ansible_os_family == "Debian""
  - name: restart_httpd
    service: 
      name: httpd
      enabled: yes
      state: retsrated
    when: ansible_os_family == "Redhat"
