---
- hosts: all
  become: yes
  tasks:
  - name: install git
    apt:
      name: git
      update_cache: yes
      state: present
  - name: install git in centos
    yum:
      name: git
      state: present

