---
- hosts: all
  become: yes
  vars:
    - myname: Surya template
  tasks:
  - name: create a file with static copy.
    copy:
      src: hello.txt
      dest: /home/ansible/hello
  - name: create a file with dynamic copy.
    template:
      src: message.j2
      dest: /home/ansible/message
 

